removal of ulnoiot in favor of iotempower

diff --git a/bin/accesspoint b/bin/accesspoint
--- a/bin/accesspoint
+++ b/bin/accesspoint
@@ -4,12 +4,12 @@ cat << EOF
 Syntax: accesspoint [show]
 
 accesspoint creates a local accespoint corresponding to parameters set
-in ulnoiot/etc/ulnoiot.conf.
+in iotempower/etc/iotempower.conf.
 EOF
 exit 1
 fi
 
-[ "$IOTEMPOWER_ACTIVE" = "yes" ] || { echo "IoT empower not active, aborting." 1>&2;exit 1; }
+[ "$IOTEMPOWER_ACTIVE" = "yes" ] || { echo "IoTempower not active, aborting." 1>&2;exit 1; }
 
 if [[ "$1" != "show" ]]; then
     ufw_active=""
diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -10,7 +10,7 @@ deploy help
 exit 1
 fi
 
-[ "$IOTEMPOWER_ACTIVE" = "yes" ] || { echo "IoT empower not active, aborting." 1>&2;exit 1; }
+[ "$IOTEMPOWER_ACTIVE" = "yes" ] || { echo "IoTempower not active, aborting." 1>&2;exit 1; }
 
 if [[ -e "node.conf" ]]; then  # started from node-directory
     deploy compile
diff --git a/bin/deploy_single b/bin/deploy_single
--- a/bin/deploy_single
+++ b/bin/deploy_single
@@ -10,7 +10,7 @@ EOF
 exit 1
 fi
 
-[ "$IOTEMPOWER_ACTIVE" = "yes" ] || { echo "IoT empower not active, aborting." 1>&2;exit 1; }
+[ "$IOTEMPOWER_ACTIVE" = "yes" ] || { echo "IoTempower not active, aborting." 1>&2;exit 1; }
 
 MAX_UPLOAD_TRIES=3
 ESPOTAPY="$HOME/.platformio/packages/tool-espotapy/espota.py"
@@ -93,7 +93,7 @@ if [[ -e "node.conf" ]]; then  # started from node-directory
         export PLATFORMIO_UPLOAD_PORT="/dev/$port"
         if [[ ! "$*" == *force ]]; then # usually check dongle
             dongle probe -p "$PLATFORMIO_UPLOAD_PORT" && {
-                echo "There is a ulnoiot esp dongle connected at $port."
+                echo "There is a IoTempower esp dongle connected at $port."
                 echo "Refusing to overwrite."
                 echo "If you are sure, specify force as last parameter."
                 exit 1
diff --git a/bin/fix_bin b/bin/fix_bin
--- a/bin/fix_bin
+++ b/bin/fix_bin
@@ -1,7 +1,7 @@
 #!/bin/bash
 # Fix binary links to trick shebang
 
-[ "$IOTEMPOWER_ACTIVE" = "yes" ] || { echo "IoT empower not active, aborting." 1>&2;exit 1; }
+[ "$IOTEMPOWER_ACTIVE" = "yes" ] || { echo "IoTempower not active, aborting." 1>&2;exit 1; }
 
 echo "Fixing binary links."
 
@@ -21,7 +21,7 @@ find "$IOTEMPOWER_ROOT/bin" -print0 | while read -d $'\0' file; do
     b=$(basename "$file")
     # if executable and not the shebang_run itself
     if [ "$b" != "shebang_run" \
-            -a "$b" != "ulnoiot" \
+            -a "$b" != "iotempower" \
             -a -x "$file" ]; then
         dest="$MYBIN/$b"
         rm "$dest" &> /dev/null
diff --git a/bin/get_ips b/bin/get_ips
--- a/bin/get_ips
+++ b/bin/get_ips
@@ -3,7 +3,7 @@
 #
 # if parameter ($1) is given, match against that as a topic
 
-[ "$IOTEMPOWER_ACTIVE" = "yes" ] || { echo "IoT empower not active, aborting." 1>&2;exit 1; }
+[ "$IOTEMPOWER_ACTIVE" = "yes" ] || { echo "IoTempower not active, aborting." 1>&2;exit 1; }
 
 source "$IOTEMPOWER_ROOT/bin/read_system_config"
 
@@ -20,8 +20,8 @@ if [[ "$1" ]]; then
     fi
 else # find all ending in /ip
     topic="#"
-    iplog=$(mktemp --suffix .ulnoiot.getip)
-    iplogall=$(mktemp --suffix .ulnoiot.getip)
+    iplog=$(mktemp --suffix .iotempower.getip)
+    iplogall=$(mktemp --suffix .iotempower.getip)
     echo -n "Scanning for ips"
     filter=""
     while true; do
diff --git a/bin/install_tilde_debian b/bin/install_tilde_debian
--- a/bin/install_tilde_debian
+++ b/bin/install_tilde_debian
@@ -6,17 +6,17 @@
 # Create date: 2017-07-12
 #
 
-[ "$IOTEMPOWER_ACTIVE" = "yes" ] || { echo "IoT empower not active, aborting." 1>&2;exit 1; }
+[ "$IOTEMPOWER_ACTIVE" = "yes" ] || { echo "IoTempower not active, aborting." 1>&2;exit 1; }
 
 MAKEFLAGS="BUILDVERSION=release LCFLAGS=-DT3_DONT_CHECK_VERSION LCXXFLAGS=-DT3_DONT_CHECK_VERSION -j4"
 #MAKEFLAGS=""
 
 if [[ $# -gt 1 || "$*" = "help" || "$*" = "-h" || "$*" = "--help" ]]; then
 cat << EOF
-ulnoiot tilde editor from release installer
+iotempower tilde editor from release installer
 ===========================================
 
-Welcome to the ulnoiot tilde editor for debian-systems installer (it might also
+Welcome to the IoTempower tilde editor for debian-systems installer (it might also
 work for other (non-debian-based) systems, but does not automatically install 
 dependencies for them).
 
diff --git a/bin/install_tilde_git b/bin/install_tilde_git
--- a/bin/install_tilde_git
+++ b/bin/install_tilde_git
@@ -8,7 +8,7 @@
 #echo "This is currently broken - need to check with author why."
 #exit 1
 
-[ "$IOTEMPOWER_ACTIVE" = "yes" ] || { echo "IoT empower not active, aborting." 1>&2;exit 1; }
+[ "$IOTEMPOWER_ACTIVE" = "yes" ] || { echo "IoTempower not active, aborting." 1>&2;exit 1; }
 
 #MAKEFLAGS="BUILDVERSION=release LCFLAGS=-DT3_DONT_CHECK_VERSION LCXXFLAGS=-DT3_DONT_CHECK_VERSION -j4"
 MAKEFLAGS="LCFLAGS=-DT3_DONT_CHECK_VERSION LCXXFLAGS=-DT3_DONT_CHECK_VERSION -j4"
@@ -16,10 +16,10 @@ MAKEFLAGS="LCFLAGS=-DT3_DONT_CHECK_VERSION LCXXFLAGS=-DT3_DONT_CHECK_VERSION -j4
 
 if [[ $# -gt 1 || "$*" = "help" || "$*" = "-h" || "$*" = "--help" ]]; then
 cat << EOF
-ulnoiot tilde editor from git installer
+iotempower tilde editor from git installer
 =======================================
 
-Welcome to the ulnoiot tilde editor for debian-systems installer (it might also
+Welcome to the iotempower tilde editor for debian-systems installer (it might also
 work for other systems, but does nto automatically install dependencies).
 
 Run as:
@@ -70,12 +70,12 @@ if [[ ! -d "$TILDEDIR" || "$*" = "clean" ]]; then
     git clone https://github.com/gphalkes/t3window ${libp}t3window$gitver
     git clone https://github.com/ulno/t3widget ${libp}t3widget$gitver
     #cd ${libp}t3widget$gitver
-    #git checkout tags/version-0.5.4 -b ulnoiot
+    #git checkout tags/version-0.5.4 -b iotempower
     #cd ..
     git clone https://github.com/gphalkes/t3highlight ${libp}t3highlight$gitver
     git clone https://github.com/gphalkes/tilde tilde$gitver
     #cd tilde$gitver
-    #git checkout tags/version-0.3.9 -b ulnoiot
+    #git checkout tags/version-0.3.9 -b iotempower
     #cd ..
     wget https://os.ghalkes.nl/LLnextgen/releases/LLnextgen-0.5.5.tgz
     tar xzf LLnextgen-0.5.5.tgz
diff --git a/bin/install_tilde_release b/bin/install_tilde_release
--- a/bin/install_tilde_release
+++ b/bin/install_tilde_release
@@ -6,17 +6,17 @@
 # Create date: 2018-12-04
 #
 
-[ "$IOTEMPOWER_ACTIVE" = "yes" ] || { echo "IoT empower not active, aborting." 1>&2;exit 1; }
+[ "$IOTEMPOWER_ACTIVE" = "yes" ] || { echo "IoTempower not active, aborting." 1>&2;exit 1; }
 
 MAKEFLAGS="BUILDVERSION=release LCFLAGS=-DT3_DONT_CHECK_VERSION LCXXFLAGS=-DT3_DONT_CHECK_VERSION -j4"
 #MAKEFLAGS=""
 
 if [[ $# -gt 1 || "$*" = "help" || "$*" = "-h" || "$*" = "--help" ]]; then
 cat << EOF
-ulnoiot tilde editor from release installer
+iotempower tilde editor from release installer
 ===========================================
 
-Welcome to the ulnoiot tilde editor release installer.
+Welcome to the iotempower tilde editor release installer.
 
 Run as:
 install_tilde_release [clean]
@@ -36,7 +36,7 @@ DO_INSTALL=sudo
 export LD_LIBRARY_PATH="$PREFIX/lib:$LD_LIBRARY_PATH"
 export LD_RUN_PATH="$PREFIX/lib:$LD_RUN_PATH"
 export PKG_CONFIG_PATH="$PREFIX/lib/pkgconfig:$PKG_CONFIG_PATH"
-# overwrite install from ulnoiot
+# overwrite install from iotempower
 export PATH="/usr/bin:$PATH"
 
 if [[ ! -d "$TILDEDIR" || "$*" = "clean" ]]; then
diff --git a/bin/iot_doc b/bin/iot_doc
--- a/bin/iot_doc
+++ b/bin/iot_doc
@@ -19,7 +19,7 @@ if [[ $# -gt 1 || "$*" = "help" || "$*" = "-h" || "$*" = "--help" ]]; then
     exit 1
 fi
 
-[ "$IOTEMPOWER_ACTIVE" = "yes" ] || { echo "IoT empower not active, aborting." 1>&2;exit 1; }
+[ "$IOTEMPOWER_ACTIVE" = "yes" ] || { echo "IoTempower not active, aborting." 1>&2;exit 1; }
 
 cd "$IOTEMPOWER_ROOT/doc"
 
diff --git a/bin/iot_menu b/bin/iot_menu
--- a/bin/iot_menu
+++ b/bin/iot_menu
@@ -5,7 +5,7 @@ cat << EOF
 Syntax: ulnoiot_shell
 
 Allow to execute common actions with text/terminal-user-interface interface
-for ulnoiot.
+for iotempower.
 
 EOF
 }
@@ -15,7 +15,7 @@ if [[ $# -gt 0 || "$*" = "help" || "$*" = "-h" || "$*" = "--help" ]]; then
     exit 1
 fi
 
-[ "$IOTEMPOWER_ACTIVE" = "yes" ] || { echo "IoT empower not active, aborting." 1>&2;exit 1; }
+[ "$IOTEMPOWER_ACTIVE" = "yes" ] || { echo "IoTempower not active, aborting." 1>&2;exit 1; }
 
 export NODE_PATH="/usr/lib/node_modules:$IOTEMPOWER_LOCAL/node_modules"
 exec node "$IOTEMPOWER_ROOT/bin/user_menu.js"
diff --git a/bin/iot_upgrade b/bin/iot_upgrade
--- a/bin/iot_upgrade
+++ b/bin/iot_upgrade
@@ -4,18 +4,18 @@ if [[ $# -gt 0 || "$*" = "help" || "$*" = "-h" || "$*" = "--help" ]]; then
 cat << EOF
 Syntax: ulnoiot_upgrade
 
-Update current version ulnoiot with newest version from git repository.
+Update current version iotempower with newest version from git repository.
 This means, pulling a new version from the git repository, fixing shebangs
 in binaries, building new view of web documentation, and cleaning up the cache.
 EOF
 exit 1
 fi
 
-[ "$IOTEMPOWER_ACTIVE" = "yes" ] || { echo "IoT empower not active, aborting." 1>&2;exit 1; }
+[ "$IOTEMPOWER_ACTIVE" = "yes" ] || { echo "IoTempower not active, aborting." 1>&2;exit 1; }
 
 
 cd "$IOTEMPOWER_ROOT"
-echo "Upgrading ulnoiot."
+echo "Upgrading iotempower."
 
 echo "Getting changes from git."
 git pull
@@ -30,6 +30,6 @@ rm -rf "$IOTEMPOWER_COMPILE_CACHE/src"
 rm -rf "$IOTEMPOWER_COMPILE_CACHE/lib"
 
 # Create web-viewable documentation
-ulnoiot doc make
+iot doc make
 
 echo "Upgrade finished."
diff --git a/bin/mqtt_listen b/bin/mqtt_listen
--- a/bin/mqtt_listen
+++ b/bin/mqtt_listen
@@ -16,7 +16,7 @@ EOF
 exit 1
 fi
 
-[ "$IOTEMPOWER_ACTIVE" = "yes" ] || { echo "IoT empower not active, aborting." 1>&2;exit 1; }
+[ "$IOTEMPOWER_ACTIVE" = "yes" ] || { echo "IoTempower not active, aborting." 1>&2;exit 1; }
 
 if [[ -e "node.conf" || -e "../node.conf" ]]; then  # started from node-directory
     source "$IOTEMPOWER_ROOT/bin/read_node_config"
diff --git a/bin/restview_starter b/bin/restview_starter
--- a/bin/restview_starter
+++ b/bin/restview_starter
@@ -1,18 +1,18 @@
 #!/bin/bash
-# TUDO: as ulnoiot documentation is now creasted in sphinx, consider retiring this
+# TUDO: as iotempower documentation is now creasted in sphinx, consider retiring this
 
 if [[ $# -gt 0 || "$*" = "help" || "$*" = "-h" || "$*" = "--help" ]]; then
 cat << EOF
 Syntax: restview_starter
 
-Start restview (for viewing ulnoiot documentation in a browser)
+Start restview (for viewing IoTempower documentation in a browser)
 in a loop (restart when exit).
 
 EOF
 exit 1
 fi
 
-[ "$IOTEMPOWER_ACTIVE" = "yes" ] || { echo "IoT empower not active, aborting." 1>&2;exit 1; }
+[ "$IOTEMPOWER_ACTIVE" = "yes" ] || { echo "IoTempower not active, aborting." 1>&2;exit 1; }
 
 while true; do
     sleep 1
