shifiting to iot empower

diff --git a/bin/accesspoint b/bin/accesspoint
--- a/bin/accesspoint
+++ b/bin/accesspoint
@@ -9,7 +9,7 @@ EOF
 exit 1
 fi
 
-[ "$ULNOIOT_ACTIVE" = "yes" ] || { echo "ulnoiot not active, aborting." 1>&2;exit 1; }
+[ "$IOTEMPOWER_ACTIVE" = "yes" ] || { echo "IoT empower not active, aborting." 1>&2;exit 1; }
 
 if [[ "$1" != "show" ]]; then
     ufw_active=""
@@ -26,9 +26,9 @@ while true; do
 
     # detect output wireless network device to start AP on
     OUTPUT_WIFI=""
-    if [[ "$ULNOIOT_AP_DEVICES" ]]; then
+    if [[ "$IOTEMPOWER_AP_DEVICES" ]]; then
         available_wifi=$(echo $(ip link show|cut -d: -f2|grep " wl"|cut -b2-))
-        for possible in $(echo "$ULNOIOT_AP_DEVICES"); do
+        for possible in $(echo "$IOTEMPOWER_AP_DEVICES"); do
             if [[ "$available_wifi" =~ .*"$possible".* ]]; then
                 OUTPUT_WIFI="$possible"
                 break
@@ -39,29 +39,29 @@ while true; do
         OUTPUT_WIFI=$(ip link show|cut -d: -f2|grep " wl"|cut -b2-|tail -n1)
     fi
 
-    ULNOIOT_AP_NAME_FULL="$ULNOIOT_AP_NAME"
-    if [ "$ULNOIOT_AP_ADDID" = "yes" ]; then
+    IOTEMPOWER_AP_NAME_FULL="$IOTEMPOWER_AP_NAME"
+    if [ "$IOTEMPOWER_AP_ADDID" = "yes" ]; then
         # add prefix to essid based on network adapter for unique class setup
         OUTPUT_MAC=$(ip link show "$OUTPUT_WIFI"|tail -n1|\
                 cut -d\  -f6|sed s/://g|cut -b7-)
-        ULNOIOT_AP_NAME_FULL="${ULNOIOT_AP_NAME}-$OUTPUT_MAC"
+        IOTEMPOWER_AP_NAME_FULL="${IOTEMPOWER_AP_NAME}-$OUTPUT_MAC"
     fi
 
     # add network extension for making essid more unique
-    AP_NAME="$ULNOIOT_AP_NAME_FULL"
+    AP_NAME="$IOTEMPOWER_AP_NAME_FULL"
 
-    PASSWORD="$ULNOIOT_AP_PASSWORD"
+    PASSWORD="$IOTEMPOWER_AP_PASSWORD"
 
-    CHANNEL="$ULNOIOT_AP_CHANNEL"
+    CHANNEL="$IOTEMPOWER_AP_CHANNEL"
     if [ "$CHANNEL" = "random" ]; then
         # pick channel randomly
         CHANNEL=$(shuf -n 1 -e 2 3 4 5 7 8 9 10)
     fi
 
-    IP="$ULNOIOT_AP_IP"
+    IP="$IOTEMPOWER_AP_IP"
 
     HIDDEN=""
-    if [[ "$ULNOIOT_AP_HIDDEN" = "yes" ]]; then
+    if [[ "$IOTEMPOWER_AP_HIDDEN" = "yes" ]]; then
         HIDDEN="--hidden"
     fi
 
@@ -71,15 +71,15 @@ while true; do
         exit 0
     fi
 
-    mkdir -p "$ULNOIOT_ROOT/tmp"
-    HOSTFILE="$ULNOIOT_ROOT/tmp/ap-host"
+    mkdir -p "$IOTEMPOWER_ROOT/tmp"
+    HOSTFILE="$IOTEMPOWER_ROOT/tmp/ap-host"
     cat << EOF > "$HOSTFILE"
-$ULNOIOT_AP_IP $ULNOIOT_AP_HOSTNAME
+$IOTEMPOWER_AP_IP $IOTEMPOWER_AP_HOSTNAME
 EOF
 
 
     HOSTAPD_EXTRA=""
-    if [[ "$ULNOIOT_AP_BRIDGE" ]]; then
+    if [[ "$IOTEMPOWER_AP_BRIDGE" ]]; then
         HOSTAPD_EXTRA="--hostapd-extra bridge=br0"
     fi
 
@@ -97,11 +97,11 @@ EOF
     sudo iptables -t nat -F
     sudo iptables -t mangle -F
     sudo iptables -X
-    if [[ "$ULNOIOT_AP_BRIDGE" ]]; then
+    if [[ "$IOTEMPOWER_AP_BRIDGE" ]]; then
         sudo ifconfig br0 down
         sudo brctl delbr br0
         sudo brctl addbr br0
-        sudo brctl addif br0 "$ULNOIOT_AP_BRIDGE"
+        sudo brctl addif br0 "$IOTEMPOWER_AP_BRIDGE"
         sudo ifconfig br0 "$IP"
     fi
 # sleep needs to be controlled from soemwhere outside this
@@ -112,7 +112,7 @@ EOF
     # on void linux
     # enable ip-forwarding
     sudo sysctl -w net.ipv4.ip_forward=1
-    sudo "$ULNOIOT_EXTERNAL/create_ap/create_ap" \
+    sudo "$IOTEMPOWER_EXTERNAL/create_ap/create_ap" \
         -c "$CHANNEL" $HIDDEN \
         -g "$IP" \
         $HOSTAPD_EXTRA \
@@ -120,12 +120,12 @@ EOF
         "$OUTPUT_WIFI" "$INPUT_DEVICE" "$AP_NAME" "$PASSWORD" &
     ap_id=$!
     sleep 7 # let ap start up
-    if [[ "$ULNOIOT_AP_BRIDGE" ]]; then
+    if [[ "$IOTEMPOWER_AP_BRIDGE" ]]; then
         # fix ip address
         sudo ifconfig "$OUTPUT_WIFI" 0.0.0.0
         sudo ifconfig br0 "$IP"
         sudo iptables -t nat -D POSTROUTING 1
-        sudo iptables -t nat -A POSTROUTING -s $ULNOIOT_AP_IP/24 \
+        sudo iptables -t nat -A POSTROUTING -s $IOTEMPOWER_AP_IP/24 \
                 -o "$INPUT_DEVICE" -j MASQUERADE
     fi
     # make sure to restore firewall
diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -10,7 +10,7 @@ deploy help
 exit 1
 fi
 
-[ "$ULNOIOT_ACTIVE" = "yes" ] || { echo "ulnoiot not active, aborting." 1>&2;exit 1; }
+[ "$IOTEMPOWER_ACTIVE" = "yes" ] || { echo "IoT empower not active, aborting." 1>&2;exit 1; }
 
 if [[ -e "node.conf" ]]; then  # started from node-directory
     deploy compile
@@ -24,7 +24,7 @@ if [[ -e "node.conf" ]]; then  # started from node-directory
 else # started from somewhere else, so search for node.conf in subdirs
 
     # first search if there is a system.conf, exit if not
-    source "$ULNOIOT_ROOT/bin/read_system_config"
+    source "$IOTEMPOWER_ROOT/bin/read_system_config"
 
     path="$(pwd)"
 
diff --git a/bin/create_node_template b/bin/create_node_template
--- a/bin/create_node_template
+++ b/bin/create_node_template
@@ -10,7 +10,7 @@ EOF
 exit 1
 fi
 
-[ "$ULNOIOT_ACTIVE" = "yes" ] || { echo "ulnoiot not active, aborting." 1>&2;exit 1; }
+[ "$IOTEMPOWER_ACTIVE" = "yes" ] || { echo "IoT empower not active, aborting." 1>&2;exit 1; }
 
 name="new-node"
 if [[ "$1" ]]; then
@@ -24,5 +24,5 @@ if [[ -e "$name" ]]; then
     echo "Folder $name (or a file with that name) already exists, please rename first."
     exit 1
 else
-    cp -a "$ULNOIOT_ROOT/lib/system_template/node_template" "$name" && echo "Successfully created."
+    cp -a "$IOTEMPOWER_ROOT/lib/system_template/node_template" "$name" && echo "Successfully created."
 fi
diff --git a/bin/deploy b/bin/deploy
--- a/bin/deploy
+++ b/bin/deploy
@@ -48,9 +48,9 @@ fi
 
 # TODO: add option to specify input file with list of specific nodes to deploy
 
-[ "$ULNOIOT_ACTIVE" = "yes" ] || { echo "ulnoiot not active, aborting." 1>&2;exit 1; }
+[ "$IOTEMPOWER_ACTIVE" = "yes" ] || { echo "IoT empower not active, aborting." 1>&2;exit 1; }
 
-export ULNOIOT_DEPLOY=active
+export IOTEMPOWER_DEPLOY=active
 
 # use tmp directory as refreshed at restart/crash
 LOCK="/tmp/.net.ulno.ulnoiot.deploy_lock"
@@ -70,7 +70,7 @@ if [[ -e "node.conf" ]]; then  # started from node-directory
 else # started from somewhere else, so search for node.conf in subdirs
 
     # first search if there is a system.conf, exit if not
-    source "$ULNOIOT_ROOT/bin/read_system_config"
+    source "$IOTEMPOWER_ROOT/bin/read_system_config"
 
 
     path="$(pwd)"
diff --git a/bin/deploy_single b/bin/deploy_single
--- a/bin/deploy_single
+++ b/bin/deploy_single
@@ -1,5 +1,5 @@
 #!/bin/bash
-if [[ $# -gt 4 || "$*" = "help" || "$*" = "-h" || "$*" = "--help" || "$ULNOIOT_DEPLOY" != active ]]; then
+if [[ $# -gt 4 || "$*" = "help" || "$*" = "-h" || "$*" = "--help" || "$IOTEMPOWER_DEPLOY" != active ]]; then
 cat << EOF
 Syntax: deploy_single
 
@@ -10,13 +10,13 @@ EOF
 exit 1
 fi
 
-[ "$ULNOIOT_ACTIVE" = "yes" ] || { echo "ulnoiot not active, aborting." 1>&2;exit 1; }
+[ "$IOTEMPOWER_ACTIVE" = "yes" ] || { echo "IoT empower not active, aborting." 1>&2;exit 1; }
 
 MAX_UPLOAD_TRIES=3
 ESPOTAPY="$HOME/.platformio/packages/tool-espotapy/espota.py"
 
 if [[ -e "node.conf" ]]; then  # started from node-directory
-    source "$ULNOIOT_ROOT/bin/read_node_config"
+    source "$IOTEMPOWER_ROOT/bin/read_node_config"
     export board # for platformio.ini
 
     port=""
@@ -25,7 +25,7 @@ if [[ -e "node.conf" ]]; then  # started from node-directory
     pio_upload="-t upload"
     adopt=""
 
-    platform_folder="$ULNOIOT_ROOT/lib/node_types/$board"
+    platform_folder="$IOTEMPOWER_ROOT/lib/node_types/$board"
 
     # check key-file and eventually regenerate
     KEYFILE=key.txt
@@ -102,7 +102,7 @@ if [[ -e "node.conf" ]]; then  # started from node-directory
     fi
 
     prepare_build_dir cache
-    cd "$ULNOIOT_COMPILE_CACHE"
+    cd "$IOTEMPOWER_COMPILE_CACHE"
 
     platformio run $pio_upload || { echo "Trouble compiling or flashing new firmware, check errors."; exit 1; }
     
diff --git a/bin/dongle b/bin/dongle
--- a/bin/dongle
+++ b/bin/dongle
@@ -4,7 +4,7 @@
 # TODO: help
 #
 
-[ "$ULNOIOT_ACTIVE" = "yes" ] || { echo "ulnoiot not active, aborting." 1>&2;exit 1; }
+[ "$IOTEMPOWER_ACTIVE" = "yes" ] || { echo "IoT empower not active, aborting." 1>&2;exit 1; }
 
 daemon_fifo=/var/tmp/ulnoiot_dongle
 daemon_port="$daemon_fifo.port"
@@ -34,9 +34,9 @@ if [[ "$command" = flash ]]; then
         port=/dev/$(find_esp_port "$2" nodongle)
     fi
     echo "Flashing dongle on port $port..."
-    python3 "$ULNOIOT_ROOT/bin/dongle_display.py" -p "$port" \
+    python3 "$IOTEMPOWER_ROOT/bin/dongle_display.py" -p "$port" \
         "Updating\\\\nfirmware...\\\\n\\\\nPlease wait."
-    cd "$ULNOIOT_ROOT/lib/esp_dongle"
+    cd "$IOTEMPOWER_ROOT/lib/esp_dongle"
     export PLATFORMIO_UPLOAD_PORT="$port"
     platformio run -t upload
     result=$?
@@ -69,9 +69,9 @@ elif [[ "$command" = daemon ]]; then
         echo "$port" > "$daemon_port"
         echo "Starting daemon on $port."
         mkfifo -m 600 "$daemon_fifo"
-    #    python3 "$ULNOIOT_ROOT/bin/dongle_daemon.py" "$@" <"$daemon_fifo"
+    #    python3 "$IOTEMPOWER_ROOT/bin/dongle_daemon.py" "$@" <"$daemon_fifo"
         # not sure why I have to use tail for the fifo and not <$daemon_fifo
-        python3 "$ULNOIOT_ROOT/bin/dongle_daemon.py" -i "$daemon_fifo" -p "$port" "$@"
+        python3 "$IOTEMPOWER_ROOT/bin/dongle_daemon.py" -i "$daemon_fifo" -p "$port" "$@"
         rm -f "$daemon_fifo" "$daemon_port"
     else
         echo "Dongle not found."
@@ -89,9 +89,9 @@ else
     port=""
     port=$(cat "$daemon_port" 2>/dev/null)
     if [[ "$port" ]]; then
-        python3 "$ULNOIOT_ROOT/bin/dongle_$command.py" -p "$port" "$@"
+        python3 "$IOTEMPOWER_ROOT/bin/dongle_$command.py" -p "$port" "$@"
     else
-        python3 "$ULNOIOT_ROOT/bin/dongle_$command.py" "$@"
+        python3 "$IOTEMPOWER_ROOT/bin/dongle_$command.py" "$@"
     fi
     result=$?
     dongle_connect
diff --git a/bin/fix_bin b/bin/fix_bin
--- a/bin/fix_bin
+++ b/bin/fix_bin
@@ -1,23 +1,23 @@
 #!/bin/bash
 # Fix binary links to trick shebang
 
-[ "$ULNOIOT_ACTIVE" = "yes" ] || { echo "ulnoiot not active, aborting." 1>&2;exit 1; }
+[ "$IOTEMPOWER_ACTIVE" = "yes" ] || { echo "IoT empower not active, aborting." 1>&2;exit 1; }
 
 echo "Fixing binary links."
 
 #### create the fixed binary directory
-MYBIN="$ULNOIOT_LOCAL/bin"
+MYBIN="$IOTEMPOWER_LOCAL/bin"
 rm -rf "$MYBIN" &> /dev/null
 mkdir -p "$MYBIN"
 # create the fixed runner
 SBRUN="$MYBIN/shebang_run"
 rm "$SBRUN" &> /dev/null
 echo "#!$(which bash)" > "$SBRUN"
-tail -n+2 "$ULNOIOT_ROOT/bin/shebang_run" >> "$SBRUN"
+tail -n+2 "$IOTEMPOWER_ROOT/bin/shebang_run" >> "$SBRUN"
 chmod a+x "$SBRUN"
 
 # create representative links for all files from the bin drectory
-find "$ULNOIOT_ROOT/bin" -print0 | while read -d $'\0' file; do
+find "$IOTEMPOWER_ROOT/bin" -print0 | while read -d $'\0' file; do
     b=$(basename "$file")
     # if executable and not the shebang_run itself
     if [ "$b" != "shebang_run" \
diff --git a/bin/get_ips b/bin/get_ips
--- a/bin/get_ips
+++ b/bin/get_ips
@@ -3,15 +3,15 @@
 #
 # if parameter ($1) is given, match against that as a topic
 
-[ "$ULNOIOT_ACTIVE" = "yes" ] || { echo "ulnoiot not active, aborting." 1>&2;exit 1; }
+[ "$IOTEMPOWER_ACTIVE" = "yes" ] || { echo "IoT empower not active, aborting." 1>&2;exit 1; }
 
-source "$ULNOIOT_ROOT/bin/read_system_config"
+source "$IOTEMPOWER_ROOT/bin/read_system_config"
 
 
 if [[ "$1" ]]; then
     topic="$1/ip"
     result=$(timeout --foreground 2 mosquitto_sub -C 1 $filter -v \
-            -h "$ULNOIOT_MQTT_HOST" -t "$topic"|cut -d\  -f2)
+            -h "$IOTEMPOWER_MQTT_HOST" -t "$topic"|cut -d\  -f2)
     if [[ "$result" ]]; then
         echo "$1: $result"
     else
@@ -27,7 +27,7 @@ else # find all ending in /ip
     while true; do
         echo -n "."
         timeout --foreground 2 mosquitto_sub -C 1 $filter -v \
-            -h "$ULNOIOT_MQTT_HOST" -t "$topic" | grep "/ip " > "$iplog"
+            -h "$IOTEMPOWER_MQTT_HOST" -t "$topic" | grep "/ip " > "$iplog"
         t=$(cat "$iplog"|cut -d\   -f1)
         ip=$(cat "$iplog"|cut -d\  -f2)
         if [[ ! "$t" ]]; then
diff --git a/bin/install_tilde_debian b/bin/install_tilde_debian
--- a/bin/install_tilde_debian
+++ b/bin/install_tilde_debian
@@ -6,7 +6,7 @@
 # Create date: 2017-07-12
 #
 
-[ "$ULNOIOT_ACTIVE" = "yes" ] || { echo "ulnoiot not active, aborting." 1>&2;exit 1; }
+[ "$IOTEMPOWER_ACTIVE" = "yes" ] || { echo "IoT empower not active, aborting." 1>&2;exit 1; }
 
 MAKEFLAGS="BUILDVERSION=release LCFLAGS=-DT3_DONT_CHECK_VERSION LCXXFLAGS=-DT3_DONT_CHECK_VERSION -j4"
 #MAKEFLAGS=""
@@ -29,7 +29,7 @@ EOF
 exit 1
 fi
 
-TILDEDIR="$ULNOIOT_EXTERNAL/tilde"
+TILDEDIR="$IOTEMPOWER_EXTERNAL/tilde"
 
 if [[ ! -d "$TILDEDIR" || "$*" = "clean" ]]; then
     /usr/bin/dpkg --search /usr/bin/dpkg &>/dev/null && {
diff --git a/bin/install_tilde_git b/bin/install_tilde_git
--- a/bin/install_tilde_git
+++ b/bin/install_tilde_git
@@ -8,7 +8,7 @@
 #echo "This is currently broken - need to check with author why."
 #exit 1
 
-[ "$ULNOIOT_ACTIVE" = "yes" ] || { echo "ulnoiot not active, aborting." 1>&2;exit 1; }
+[ "$IOTEMPOWER_ACTIVE" = "yes" ] || { echo "IoT empower not active, aborting." 1>&2;exit 1; }
 
 #MAKEFLAGS="BUILDVERSION=release LCFLAGS=-DT3_DONT_CHECK_VERSION LCXXFLAGS=-DT3_DONT_CHECK_VERSION -j4"
 MAKEFLAGS="LCFLAGS=-DT3_DONT_CHECK_VERSION LCXXFLAGS=-DT3_DONT_CHECK_VERSION -j4"
@@ -32,7 +32,7 @@ exit 1
 fi
 
 
-TILDEDIR="$ULNOIOT_EXTERNAL/tilde"
+TILDEDIR="$IOTEMPOWER_EXTERNAL/tilde"
 #gitver="-git$(date +%Y%m%d)"
 gitver=""
 #libp="lib"
@@ -101,14 +101,14 @@ export CFLAGS="-O2 -D_POSIX_C_SOURCE=200809L"
 cd "$TILDEDIR/llnextgen"
 ./configure --prefix=/usr CFLAGS="$CFLAGS"
 make $MAKEFLAGS
-strip -s -o "$ULNOIOT_LOCAL/bin/LLnextgen" "LLnextgen"
+strip -s -o "$IOTEMPOWER_LOCAL/bin/LLnextgen" "LLnextgen"
 
 cd "$TILDEDIR"
 echo "Building tilde."
 ./t3shared/doall make $MAKEFLAGS -C src
 
 echo "Installing tilde."
-strip -s -o "$ULNOIOT_LOCAL/bin/tilde" "$TILDEDIR/tilde/src/.objects/edit"
+strip -s -o "$IOTEMPOWER_LOCAL/bin/tilde" "$TILDEDIR/tilde/src/.objects/edit"
 # TODO consider:
 # link to /usr/local/bin/tilde
 # update-alternatives --install /usr/bin/editor editor /usr/local/bin/tilde 50
diff --git a/bin/iot_doc b/bin/iot_doc
--- a/bin/iot_doc
+++ b/bin/iot_doc
@@ -19,9 +19,9 @@ if [[ $# -gt 1 || "$*" = "help" || "$*" = "-h" || "$*" = "--help" ]]; then
     exit 1
 fi
 
-[ "$ULNOIOT_ACTIVE" = "yes" ] || { echo "ulnoiot not active, aborting." 1>&2;exit 1; }
+[ "$IOTEMPOWER_ACTIVE" = "yes" ] || { echo "IoT empower not active, aborting." 1>&2;exit 1; }
 
-cd "$ULNOIOT_ROOT/doc"
+cd "$IOTEMPOWER_ROOT/doc"
 
 create_doc() {
     echo "Generating man pages."
@@ -29,8 +29,8 @@ create_doc() {
     echo "Generating web-viewable documentation."
     make html
     # TODO: do eventually a matching specific version here
-    ln -s -f "$ULNOIOT_LOCAL/doc/html/doc/index-pi.html" \
-        "$ULNOIOT_LOCAL/doc/html/index.html"
+    ln -s -f "$IOTEMPOWER_LOCAL/doc/html/doc/index-pi.html" \
+        "$IOTEMPOWER_LOCAL/doc/html/index.html"
     echo "Documentation creation finished."
 }
 
@@ -47,8 +47,8 @@ case "$1" in
     serve)
         create_doc
         echo "Starting webserver for documentation. ctrl-c to stop."
-        cd "$ULNOIOT_LOCAL/doc/html"
-        exec python "$ULNOIOT_ROOT/bin/docserver.py"
+        cd "$IOTEMPOWER_LOCAL/doc/html"
+        exec python "$IOTEMPOWER_ROOT/bin/docserver.py"
         ;;
     *)
         usage
diff --git a/bin/iot_help b/bin/iot_help
--- a/bin/iot_help
+++ b/bin/iot_help
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 
-[ "$ULNOIOT_ACTIVE" = "yes" ] || { echo "ulnoiot not active, aborting." 1>&2;exit 1; }
+[ "$IOTEMPOWER_ACTIVE" = "yes" ] || { echo "IoT empower not active, aborting." 1>&2;exit 1; }
 
 HELP_PATH=doc/node_help
 # TODO: adjust path to different selected micro controllers depending on node
@@ -17,12 +17,12 @@ EOF
 # [cmd] can be any of the following:
 fi
 
-man -l "$ULNOIOT_LOCAL/doc/man/$1.1" 2>/dev/null || \
-    man -l "$ULNOIOT_LOCAL/doc/man/commands.1"
+man -l "$IOTEMPOWER_LOCAL/doc/man/$1.1" 2>/dev/null || \
+    man -l "$IOTEMPOWER_LOCAL/doc/man/commands.1"
 
 # obsolete
 # comma=""
-# ls "$ULNOIOT_ROOT/$HELP_PATH/"*.txt | while read f; do
+# ls "$IOTEMPOWER_ROOT/$HELP_PATH/"*.txt | while read f; do
 #     f=$(basename "$f")
 #     if [[ ${f:0:1} != "_" ]]; then
 #         echo -n $comma${f:0:-4}
@@ -37,13 +37,13 @@ man -l "$ULNOIOT_LOCAL/doc/man/$1.1" 2>/dev/null || \
 # fi
 
 
-# cd "$ULNOIOT_ROOT"
+# cd "$IOTEMPOWER_ROOT"
 
 # function help() {
 #     local m
 #     local p
 #     local l
-#     p="$ULNOIOT_ROOT/$HELP_PATH/$1.txt"
+#     p="$IOTEMPOWER_ROOT/$HELP_PATH/$1.txt"
 #     { cat "$p"; echo; } | while read l; do
 #         if [[ "$l" = "!!"* ]]; then
 #             if [[ "$l" =~ '!!help("'(.*)'")' ]]; then
diff --git a/bin/iot_install b/bin/iot_install
--- a/bin/iot_install
+++ b/bin/iot_install
@@ -2,17 +2,17 @@
 # if not available, install all dependencies
 # and also allow to fix shebangs in local bin folder
 #
-# check if everything from ULNOIOT_EXTERNAL is downloaded and accessable
+# check if everything from IOTEMPOWER_EXTERNAL is downloaded and accessable
 # if not asks to install it
 #
-# if called as check_install clean, it will delete content of ULNOIOT_EXTERNAL and
+# if called as check_install clean, it will delete content of IOTEMPOWER_EXTERNAL and
 # re-download everything
 #
 # Author: ulno
 # Create date: 2017-05-17
 #
 
-[ "$ULNOIOT_ACTIVE" = "yes" ] || { echo "ulnoiot not active, aborting." 1>&2;exit 1; }
+[ "$IOTEMPOWER_ACTIVE" = "yes" ] || { echo "IoT empower not active, aborting." 1>&2;exit 1; }
 
 
 function welcome() {
@@ -41,13 +41,13 @@ EOF
 if [[ "$1" == clean ]]; then
   echo "Deleting external cache."
   echo
-  rm -rf "$ULNOIOT_VPYTHON"
-  rm -rf "$ULNOIOT_EXTERNAL"
+  rm -rf "$IOTEMPOWER_VPYTHON"
+  rm -rf "$IOTEMPOWER_EXTERNAL"
 fi
 
 # check if virtualenv is configured
-if [[ -e "$ULNOIOT_VPYTHON/bin/activate" ]]; then # check for existing venv
-    source "$ULNOIOT_VPYTHON/bin/activate"
+if [[ -e "$IOTEMPOWER_VPYTHON/bin/activate" ]]; then # check for existing venv
+    source "$IOTEMPOWER_VPYTHON/bin/activate"
 else
     welcome
     read answer
@@ -66,17 +66,17 @@ else
     fi
     # TODO: recheck, installation seems to fail first time -> path problems (wrong pip used?)
     # install virtualenv for python2 for platformio
-    mkdir -p "$ULNOIOT_VPYTHON2"
-    virtualenv -p "$(which python2)" "$ULNOIOT_VPYTHON2"
-    source "$ULNOIOT_VPYTHON2/bin/activate"
+    mkdir -p "$IOTEMPOWER_VPYTHON2"
+    virtualenv -p "$(which python2)" "$IOTEMPOWER_VPYTHON2"
+    source "$IOTEMPOWER_VPYTHON2/bin/activate"
     pip install --upgrade pip
     pip install --upgrade platformio
     deactivate
     
     # install virtualenv
-    mkdir -p "$ULNOIOT_VPYTHON"
-    virtualenv -p "$(which python3)" "$ULNOIOT_VPYTHON"
-    source "$ULNOIOT_VPYTHON/bin/activate"
+    mkdir -p "$IOTEMPOWER_VPYTHON"
+    virtualenv -p "$(which python3)" "$IOTEMPOWER_VPYTHON"
+    source "$IOTEMPOWER_VPYTHON/bin/activate"
     pip install --upgrade pip
     # dependencies
     pip install pyserial
@@ -94,37 +94,37 @@ else
     # TODO: fix more dependencies
     # Termux needs: ncurses-utils
     # esptool
-    git clone https://github.com/espressif/esptool "$ULNOIOT_EXTERNAL/esptool.git"
-    cd "$ULNOIOT_EXTERNAL/esptool.git"
+    git clone https://github.com/espressif/esptool "$IOTEMPOWER_EXTERNAL/esptool.git"
+    cd "$IOTEMPOWER_EXTERNAL/esptool.git"
     python setup.py install
-    ln -s "$ULNOIOT_EXTERNAL/esptool.git/esptool.py" "$ULNOIOT_VPYTHON/bin/esptool"
+    ln -s "$IOTEMPOWER_EXTERNAL/esptool.git/esptool.py" "$IOTEMPOWER_VPYTHON/bin/esptool"
 
     ## mpfshell - upy specific
-    #git clone https://github.com/ulno/mpfshell "$ULNOIOT_EXTERNAL/mpfshell.git"
-    #cd "$ULNOIOT_EXTERNAL/mpfshell.git"
+    #git clone https://github.com/ulno/mpfshell "$IOTEMPOWER_EXTERNAL/mpfshell.git"
+    #cd "$IOTEMPOWER_EXTERNAL/mpfshell.git"
     #python setup.py install
 
     # accesspoint
-    git clone https://github.com/ulno/create_ap "$ULNOIOT_EXTERNAL/create_ap"
-    #cd "$ULNOIOT_EXTERNAL/create_ap"
+    git clone https://github.com/ulno/create_ap "$IOTEMPOWER_EXTERNAL/create_ap"
+    #cd "$IOTEMPOWER_EXTERNAL/create_ap"
 
 #    # pyminifier
-#    git clone https://github.com/liftoff/pyminifier "$ULNOIOT_EXTERNAL/pyminifier"
-#    cd "$ULNOIOT_EXTERNAL/pyminifier"
+#    git clone https://github.com/liftoff/pyminifier "$IOTEMPOWER_EXTERNAL/pyminifier"
+#    cd "$IOTEMPOWER_EXTERNAL/pyminifier"
 #    python setup.py install
 
 #    # download firmware
-#    mkdir -p "$ULNOIOT_EXTERNAL/firmware"
-#    cd "$ULNOIOT_EXTERNAL/firmware"
-#    "$ULNOIOT_ROOT/bin/download_firmware"
-#    "$ULNOIOT_ROOT/bin/firmware" download
+#    mkdir -p "$IOTEMPOWER_EXTERNAL/firmware"
+#    cd "$IOTEMPOWER_EXTERNAL/firmware"
+#    "$IOTEMPOWER_ROOT/bin/download_firmware"
+#    "$IOTEMPOWER_ROOT/bin/firmware" download
 
-    cd "$ULNOIOT_LOCAL"
+    cd "$IOTEMPOWER_LOCAL"
     npm install terminal-kit
 
     popd  &> /dev/null
 
-    bash "$ULNOIOT_ROOT/bin/fix_bin"
+    bash "$IOTEMPOWER_ROOT/bin/fix_bin"
 
     update_cache
 
diff --git a/bin/iot_menu b/bin/iot_menu
--- a/bin/iot_menu
+++ b/bin/iot_menu
@@ -15,7 +15,7 @@ if [[ $# -gt 0 || "$*" = "help" || "$*" = "-h" || "$*" = "--help" ]]; then
     exit 1
 fi
 
-[ "$ULNOIOT_ACTIVE" = "yes" ] || { echo "ulnoiot not active, aborting." 1>&2;exit 1; }
+[ "$IOTEMPOWER_ACTIVE" = "yes" ] || { echo "IoT empower not active, aborting." 1>&2;exit 1; }
 
-export NODE_PATH="/usr/lib/node_modules:$ULNOIOT_LOCAL/node_modules"
-exec node "$ULNOIOT_ROOT/bin/user_menu.js"
+export NODE_PATH="/usr/lib/node_modules:$IOTEMPOWER_LOCAL/node_modules"
+exec node "$IOTEMPOWER_ROOT/bin/user_menu.js"
diff --git a/bin/iot_upgrade b/bin/iot_upgrade
--- a/bin/iot_upgrade
+++ b/bin/iot_upgrade
@@ -11,10 +11,10 @@ EOF
 exit 1
 fi
 
-[ "$ULNOIOT_ACTIVE" = "yes" ] || { echo "ulnoiot not active, aborting." 1>&2;exit 1; }
+[ "$IOTEMPOWER_ACTIVE" = "yes" ] || { echo "IoT empower not active, aborting." 1>&2;exit 1; }
 
 
-cd "$ULNOIOT_ROOT"
+cd "$IOTEMPOWER_ROOT"
 echo "Upgrading ulnoiot."
 
 echo "Getting changes from git."
@@ -26,8 +26,8 @@ git pull
 fix_bin # prints out Fixing links
 
 echo "Cleaning source files from cache to regenerate."
-rm -rf "$ULNOIOT_COMPILE_CACHE/src"
-rm -rf "$ULNOIOT_COMPILE_CACHE/lib"
+rm -rf "$IOTEMPOWER_COMPILE_CACHE/src"
+rm -rf "$IOTEMPOWER_COMPILE_CACHE/lib"
 
 # Create web-viewable documentation
 ulnoiot doc make
diff --git a/bin/mqtt_action b/bin/mqtt_action
--- a/bin/mqtt_action
+++ b/bin/mqtt_action
@@ -28,7 +28,7 @@ exit 1
 fi
 
 
-[ "$ULNOIOT_ACTIVE" = "yes" ] || { echo "ulnoiot not active, aborting." 1>&2;exit 1; }
+[ "$IOTEMPOWER_ACTIVE" = "yes" ] || { echo "IoT empower not active, aborting." 1>&2;exit 1; }
 
 arg_topic="$1"
 trigger_type="$2"
@@ -37,7 +37,7 @@ shift 3
 
 
 if [[ -e "node.conf" || -e "../node.conf" ]]; then  # started from node-directory
-    source "$ULNOIOT_ROOT/bin/read_node_config"
+    source "$IOTEMPOWER_ROOT/bin/read_node_config"
 else # Check if in system directory and read
     source "system.conf" &> /dev/null
 fi
@@ -57,10 +57,10 @@ fi
 last_data="123ulno.net321"
 
 
-echo "Subscribing to mqtt://$ULNOIOT_MQTT_HOST/$topic " >&2
+echo "Subscribing to mqtt://$IOTEMPOWER_MQTT_HOST/$topic " >&2
 echo "with trigger $trigger_type for data $trigger_data" >&2
 echo "executing: $@ <received payload>" >&2
-mosquitto_sub -h "$ULNOIOT_MQTT_HOST" -t "$topic" \
+mosquitto_sub -h "$IOTEMPOWER_MQTT_HOST" -t "$topic" \
 |   while read data; do
         echo "mqtt_action: received $data" >&2
         changed=""
diff --git a/bin/mqtt_broker b/bin/mqtt_broker
--- a/bin/mqtt_broker
+++ b/bin/mqtt_broker
@@ -9,10 +9,10 @@ EOF
 exit 1
 fi
 
-[ "$ULNOIOT_ACTIVE" = "yes" ] || { echo "ulnoiot not active, aborting." 1>&2;exit 1; }
+[ "$IOTEMPOWER_ACTIVE" = "yes" ] || { echo "IoT empower not active, aborting." 1>&2;exit 1; }
 
 
-APTEMP="$ULNOIOT_LOCAL/tmp/mosquitto"
+APTEMP="$IOTEMPOWER_LOCAL/tmp/mosquitto"
 rm -rf "$APTEMP" &> /dev/null
 mkdir -p "$APTEMP"
 
@@ -25,26 +25,26 @@ log_dest stdout
 log_type error
 log_type warning
 bind_address 127.0.0.1
-listener 1883 $ULNOIOT_MQTT_HOST
+listener 1883 $IOTEMPOWER_MQTT_HOST
 EOF
 
 # create bridge
-if [ "$ULNOIOT_MQTT_BRIDGE_HOST" ]; then
+if [ "$IOTEMPOWER_MQTT_BRIDGE_HOST" ]; then
 
 # bridge config based on example in http://owntracks.org/booklet/guide/bridge/
 cat << EOF >> "$APTEMP/mosquitto.conf"
-connection bridge-to-$ULNOIOT_MQTT_BRIDGE_HOST
-bridge_capath $ULNOIOT_MQTT_BRIDGE_CERTPATH
+connection bridge-to-$IOTEMPOWER_MQTT_BRIDGE_HOST
+bridge_capath $IOTEMPOWER_MQTT_BRIDGE_CERTPATH
 bridge_insecure false
-address $ULNOIOT_MQTT_BRIDGE_HOST:$ULNOIOT_MQTT_BRIDGE_PORT
+address $IOTEMPOWER_MQTT_BRIDGE_HOST:$IOTEMPOWER_MQTT_BRIDGE_PORT
 cleansession false
-clientid bridge-$HOSTNAME-$ULNOIOT_MQTT_BRIDGE_HOST
+clientid bridge-$HOSTNAME-$IOTEMPOWER_MQTT_BRIDGE_HOST
 start_type automatic
-username $ULNOIOT_MQTT_BRIDGE_USER
-password $ULNOIOT_MQTT_BRIDGE_PW
+username $IOTEMPOWER_MQTT_BRIDGE_USER
+password $IOTEMPOWER_MQTT_BRIDGE_PW
 notifications false
 try_private true
-topic # both 2 ${ULNOIOT_MQTT_BRIDGE_TOPIC}/ ${ULNOIOT_MQTT_BRIDGE_TOPIC}/
+topic # both 2 ${IOTEMPOWER_MQTT_BRIDGE_TOPIC}/ ${IOTEMPOWER_MQTT_BRIDGE_TOPIC}/
 EOF
 
 fi # bridge-config
diff --git a/bin/mqtt_listen b/bin/mqtt_listen
--- a/bin/mqtt_listen
+++ b/bin/mqtt_listen
@@ -16,10 +16,10 @@ EOF
 exit 1
 fi
 
-[ "$ULNOIOT_ACTIVE" = "yes" ] || { echo "ulnoiot not active, aborting." 1>&2;exit 1; }
+[ "$IOTEMPOWER_ACTIVE" = "yes" ] || { echo "IoT empower not active, aborting." 1>&2;exit 1; }
 
 if [[ -e "node.conf" || -e "../node.conf" ]]; then  # started from node-directory
-    source "$ULNOIOT_ROOT/bin/read_node_config"
+    source "$IOTEMPOWER_ROOT/bin/read_node_config"
 else # Check if in system directory and read
     source "system.conf" &> /dev/null
 fi
@@ -42,5 +42,5 @@ else
     topic="#"
 fi
 
-echo "Subscribing and listening to mqtt://$ULNOIOT_MQTT_HOST/$topic." >&2
-mosquitto_sub -v -h "$ULNOIOT_MQTT_HOST" -t "$topic"
+echo "Subscribing and listening to mqtt://$IOTEMPOWER_MQTT_HOST/$topic." >&2
+mosquitto_sub -v -h "$IOTEMPOWER_MQTT_HOST" -t "$topic"
diff --git a/bin/prepare_build_dir b/bin/prepare_build_dir
--- a/bin/prepare_build_dir
+++ b/bin/prepare_build_dir
@@ -14,7 +14,7 @@ EOF
 exit 1
 fi
 
-[ "$ULNOIOT_ACTIVE" = "yes" ] || { echo "ulnoiot not active, aborting." 1>&2;exit 1; }
+[ "$IOTEMPOWER_ACTIVE" = "yes" ] || { echo "IoT empower not active, aborting." 1>&2;exit 1; }
 
 # TODO: remove dead links
 # TODO: only do it when no other process is active on that dir
@@ -57,28 +57,28 @@ link_type_through_base() {
 }
 
 if [[ -e "node.conf" ]]; then  # started from node-directory
-    source "$ULNOIOT_ROOT/bin/read_node_config"
+    source "$IOTEMPOWER_ROOT/bin/read_node_config"
     node_type="$board"
     
-    src_dir="$ULNOIOT_ROOT/lib/node_types/$node_type"
+    src_dir="$IOTEMPOWER_ROOT/lib/node_types/$node_type"
     dest_dir="build"
     
     if [[ "$1" == "cache" ]]; then
         rm -rf "$dest_dir" &> /dev/null
-        ln -f -s "$ULNOIOT_COMPILE_CACHE" "$dest_dir"
+        ln -f -s "$IOTEMPOWER_COMPILE_CACHE" "$dest_dir"
         # obsolet as we now compile everything in one dir and just update src
         # if [[ ! -e "$dest_dir/.pioenvs/$board" ]]; then # only create if not there yet
         #     rm -rf "$dest_dir/.piolibdeps" &>/dev/null
-        #     ln -f -s "$ULNOIOT_COMPILE_CACHE/.piolibdeps" "$dest_dir/"
+        #     ln -f -s "$IOTEMPOWER_COMPILE_CACHE/.piolibdeps" "$dest_dir/"
         #     if [[ "$board" ]]; then
         #         mkdir -p "$dest_dir/.pioenvs/$board"
-        #         for file in $(ls "$ULNOIOT_COMPILE_CACHE/.pioenvs/$board"); do
+        #         for file in $(ls "$IOTEMPOWER_COMPILE_CACHE/.pioenvs/$board"); do
         #             if [[ ! "$file" =~ ^(src|firmware.elf|firmware.bin|)$ ]]; then
-        #                 ln -f -s "$ULNOIOT_COMPILE_CACHE/.pioenvs/$board/$file" \
+        #                 ln -f -s "$IOTEMPOWER_COMPILE_CACHE/.pioenvs/$board/$file" \
         #                     "$dest_dir/.pioenvs/$board/"
         #             fi
         #         done
-        #         rsync -r "$ULNOIOT_COMPILE_CACHE/.pioenvs/$board/src/" \
+        #         rsync -r "$IOTEMPOWER_COMPILE_CACHE/.pioenvs/$board/src/" \
         #                     "$dest_dir/.pioenvs/$board/src/"
         #     fi
         # fi
@@ -117,8 +117,8 @@ EOF
 #    echo "// no wifi credentials" > "$dest_dir/src/wifi-config.h"
     fname="$dest_dir/src/wifi-config.h"
 cat > "$fname.new" << EOF
-#define WIFI_SSID "$ULNOIOT_AP_NAME_FULL"
-#define WIFI_PASSWORD "$ULNOIOT_AP_PASSWORD"
+#define WIFI_SSID "$IOTEMPOWER_AP_NAME_FULL"
+#define WIFI_PASSWORD "$IOTEMPOWER_AP_PASSWORD"
 EOF
     # only replace if it's new
     diff -q -f "$fname.new" "$fname" 2>/dev/null || mv "$fname.new" "$fname"
diff --git a/bin/restview_starter b/bin/restview_starter
--- a/bin/restview_starter
+++ b/bin/restview_starter
@@ -12,14 +12,14 @@ EOF
 exit 1
 fi
 
-[ "$ULNOIOT_ACTIVE" = "yes" ] || { echo "ulnoiot not active, aborting." 1>&2;exit 1; }
+[ "$IOTEMPOWER_ACTIVE" = "yes" ] || { echo "IoT empower not active, aborting." 1>&2;exit 1; }
 
 while true; do
     sleep 1
     # make doc directory
-    mkdir -p "$ULNOIOT_LOCAL/webdoc"
-    ln -f -s "$ULNOIOT_ROOT/doc" "$ULNOIOT_LOCAL/webdoc/doc"
-    cd "$ULNOIOT_ROOT"
+    mkdir -p "$IOTEMPOWER_LOCAL/webdoc"
+    ln -f -s "$IOTEMPOWER_ROOT/doc" "$IOTEMPOWER_LOCAL/webdoc/doc"
+    cd "$IOTEMPOWER_ROOT"
     restview -l 3000 -B . 
     sleep 1
 done
diff --git a/bin/update_cache b/bin/update_cache
--- a/bin/update_cache
+++ b/bin/update_cache
@@ -11,9 +11,9 @@ EOF
 exit 1
 fi
 
-[ "$ULNOIOT_ACTIVE" = "yes" ] || { echo "ulnoiot not active, aborting." 1>&2;exit 1; }
+[ "$IOTEMPOWER_ACTIVE" = "yes" ] || { echo "IoT empower not active, aborting." 1>&2;exit 1; }
 
-CACHE_ROOT="$ULNOIOT_LOCAL/compile_cache"
+CACHE_ROOT="$IOTEMPOWER_LOCAL/compile_cache"
 mkdir -p "$CACHE_ROOT/node"
 echo "# empty" > "$CACHE_ROOT/system.conf"
 cd "$CACHE_ROOT/node"
