preperation for transfer to template based configuration

diff --git a/bin/console b/bin/console
--- a/bin/console
+++ b/bin/console
@@ -1,22 +1,20 @@
 #!/bin/bash
 # open a repl terminal on the given port (USB..) or ip address
 # $1: suggested port or host
-# $2: webrepl password
-password="$2"
-test "$password" || password="ulnoiot"
 
 [ "$ULNOIOT_ACTIVE" = "yes" ] || { echo "ulnoiot not active, aborting." 1>&2;exit 1; }
 
-port=$(find_esp_port "$1" "$password")
-
-if [[ "$port" = tty* ]]; then
-    echo "Opening serial console on $port."
-    echo "Type help to get basic help information."
-    echo "If you do not see what you are typing, try to press"
-    echo "ctrl-B."
-    echo
-    #minicom -D "/dev/$port" -b 115000
-    miniterm.py --raw "/dev/$port" 115000
+if [ -e "node.conf" ]; then # started from node-directory -> network connect
+    source "$ULNOIOT_ROOT/bin/read_config"
+    ip=$(get_ip "$topic" 2>/dev/null|grep "$topic"|cut -d\  -f2)
+    if [ "$ip" ]; then
+        echo "Connecting to node $topic with ip $ip."
+        tail -n1 key.hex | console_netrepl "$ip"
+    else
+        echo "Couldn't find IP of node with topic $topic."
+        echo "If connected via serial or usb, try console_serial."
+        exit 1
+    fi
 else
-    mpfshell --nocache -n -c "open $port; repl"
+    console_serial "$1"
 fi
