better error reporting in mass deploy

diff --git a/bin/deploy b/bin/deploy
--- a/bin/deploy
+++ b/bin/deploy
@@ -33,7 +33,7 @@ in the current network.
 For this adoption process, it is using a locally connected ulnoiot esp dongle.
 It will not work if no dongle is locally connected.
 The respective board has to be in configuration/adopt mode (this mode
-is usually triggerd via pressing and releasing the flash key twice during
+is usually triggered via pressing and releasing the flash key twice during
 its five second power-up phase).
 
 If deploy is called from a node's parent folder, it deploys all nodes in
@@ -46,12 +46,16 @@ EOF
 exit 1
 fi
 
+# TODO: add option to specify input file with list of specific nodes to deploy
+
 [ "$ULNOIOT_ACTIVE" = "yes" ] || { echo "ulnoiot not active, aborting." 1>&2;exit 1; }
 
 export ULNOIOT_DEPLOY=active
 
 # use tmp directory as refreshed at restart/crash
 LOCK="/tmp/.net.ulno.ulnoiot.deploy_lock"
+
+FAILED_NODES="failed_nodes.txt"
 
 if [[ -e "node.conf" ]]; then  # started from node-directory
     flock -n -e -E 50 "$LOCK" deploy_single "$@"
@@ -77,12 +81,32 @@ else # started from somewhere else, so search for node.conf in subdirs
         echo "deploying of multiple nodes only works if no parameters are specified."
         exit 1
     fi
+    
+    rm -f "$FAILED_NODES"
+
     # TODO: think about running them all in parallel (or batches)
     find -name node.conf |\
         while read n; do
             cd "$path"
             cd $(dirname "$n")
             deploy # call recursive for node-dir
+            cd "$path"
+            if [[ $? -ne 0 ]]; then # failed
+                echo "$n" >> "$FAILED_NODES"
+            fi
         done
+
+    cd "$path"
+
+    if [[ -e "$FAILED_NODES" ]]; then
+        echo "The following nodes failed to deploy."
+        cat "$FAILED_NODES"
+        echo "Check log above for specific problems."
+        echo "List of failed nodes is in the file $FAILED_NODES."
+        exit 1
+    fi
+
+    echo "All nodes successfully deployed."
+    exit 0
 
 fi # not in node-dir
