update helpwer scripts to actually detect a local network also on termux

diff --git a/bin/find_local_network b/bin/find_local_network
--- a/bin/find_local_network
+++ b/bin/find_local_network
@@ -36,11 +36,25 @@ check_internet_connectivity() {
     fi
 }
 
-# Call the get_ips script and iterate over its output
+
+FIRST_HOP_IP=$(traceroute -n $TEST_IP 2>/dev/null | awk 'NR==2 {print $2}')
+
+# Check if we got a valid IP address
+if ! [[ $FIRST_HOP_IP =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+    # echo "Failed to get the IP address of the first hop."
+    FIRST_HOP_IP=""
+fi
+
+
+# Call the show_local_ips script and iterate over its output
 show_local_ips | while read -r line; do
+    if ! [[ "$FIRST_HOP_IP" ]]; then
+        echo "$line"
+        exit 0
+    fi
     iface=$(echo "$line" | awk '{print $1}')
-    ip=$(echo "$line" | awk '{print $2}')
-    if ! check_internet_connectivity "$iface"; then
+    net=$(echo "$line" | awk '{print $2}')
+    if ! check_ip_in_network "$FIRST_HOP_IP" "$net"; then
         echo "$iface $ip"
         exit 0
     fi
