mkae convinience tool default when using quiet - and refactor pi test

diff --git a/bin/iot_install b/bin/iot_install
--- a/bin/iot_install
+++ b/bin/iot_install
@@ -102,6 +102,11 @@ function init_nodejs() {
     npm init -y > /dev/null
 }
 
+function check_pi() {
+  # check if this is a raspberry pi - TODO: seems not to work, verify
+  vcgencmd version &> /dev/null
+}
+
 # make installers available in PATH
 export PATH="$IOTEMPOWER_ROOT/lib/iot_installs:$PATH"
 
@@ -183,8 +188,12 @@ else
 		answer_node_red=1
 		answer_caddy=1
 		answer_mqtt=1
-		answer_fix_pi_wifi_ap=0
-    answer_convenience=0
+    if check_pi; then
+      answer_fix_pi_wifi_ap=1
+    else
+  		answer_fix_pi_wifi_ap=0
+    fi
+    answer_convenience=1
     answer_templates=1
     answer_cache=0
     answer_upgrade=1
@@ -219,8 +228,7 @@ else
         )" n
       answer_cache=$?
 
-      # check if this is a raspberry pi
-      if vcgencmd version &> /dev/null; then
+      if check_pi; then
         # activate minimal firmware
         echo_message_read_answer "$(printf "%b\n" \
           "In order to support a larger amount of connected devices,"\
@@ -252,7 +260,10 @@ else
   fi
 
   if [[ "$answer_core" == 1 ]]; then
-    call_by_system install-general
+    if ! call_by_system install-general; then
+      echo "Installation of general requirements failed. Aborting installation."
+      exit 1
+    fi
     # python2 seems not to be necessary anymore
     # # TODO: recheck, installation seems to fail first time -> path problems (wrong pip used?)
     # # install virtualenv for python2 for platformio
diff --git a/lib/iot_installs/debian-install-general b/lib/iot_installs/debian-install-general
--- a/lib/iot_installs/debian-install-general
+++ b/lib/iot_installs/debian-install-general
@@ -24,32 +24,50 @@ if ! debian-query curl > /dev/null; then
     echo "curl has been installed successfully"
 fi
 
-# check nodejs version
-if command -v node &> /dev/null; then
-    installed_version=$(node -v 2>/dev/null| sed 's/v//') # Remove the 'v' prefix from version
-else
-    installed_version="0.0.0-notinstalled"
-fi
-
 # Define the minimum required version
 min_version="21"
 
-# Use sort with version sort flag to compare versions, and check the first line
-if [[ "$installed_version" && "$(printf "%s\n%s" "$min_version" "$installed_version" | sort -V | head -n1)" = "$min_version" ]]; then
-    if [ "$installed_version" = "$min_version" ] || [ "$(printf "%s\n%s" "$min_version" "$installed_version" | sort -V | head -n2 | tail -n1)" = "$installed_version" ]; then
-        echo "Node.js version $installed_version is installed, meets the minimum required version $min_version."
+function check_node() {
+    # check nodejs version
+    if command -v node &> /dev/null; then
+        installed_version=$(node -v 2>/dev/null| sed 's/v//') # Remove the 'v' prefix from version
     else
-        echo "Node.js version is higher than the minimum required version $min_version."
+        installed_version="0.0.0-notinstalled"
     fi
-else
-    echo "Node.js version is $installed_version, and "
-    echo "does not meet the minimum required version $min_version."
-    # install current node.js - seems to need suddenly sudo # TODO: check other install methods
-    curl -fsSL "https://deb.nodesource.com/setup_""$min_version"".x" | sudo bash -
+    # Use sort with version sort flag to compare versions, and check the first line
+    if [[ "$installed_version" && "$(printf "%s\n%s" "$min_version" "$installed_version" | sort -V | head -n1)" = "$min_version" ]]; then
+        if [ "$installed_version" = "$min_version" ] || [ "$(printf "%s\n%s" "$min_version" "$installed_version" | sort -V | head -n2 | tail -n1)" = "$installed_version" ]; then
+            echo "Node.js version $installed_version is installed, meets the minimum required version $min_version."
+        else
+            echo "Node.js version is higher than the minimum required version $min_version."
+        fi
+        return 0 # all good
+    else
+        echo "Node.js version is $installed_version, and "
+        echo "does not meet the minimum required version $min_version."
+        return 1
+    fi
+}
+
+if ! check_node; then
+    # # the curl thing seems broken
+    # # install current node.js - seems to need suddenly sudo # TODO: check other install methods
+    # curl -fsSL "https://deb.nodesource.com/setup_""$min_version"".x" | sudo bash -
+
+    echo "Trying to install current node version."
+    sudo apt-get install -y ca-certificates curl gnupg
+    curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
+    NODE_MAJOR=$min_version
+    echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | sudo tee /etc/apt/sources.list.d/nodesource.list
+    sudo apt-get update && sudo apt-get install nodejs -y
+    if ! check_node; then
+        echo "A current node version could not be installed."
+        exit 1
+    fi
 fi
 
 # procps allows pkill and ps
-PACKAGE_LIST="build-essential git procps mosquitto-clients virtualenv python3-venv python3-dev make rsync haveged jq nodejs"
+PACKAGE_LIST="build-essential git procps mosquitto-clients virtualenv python3-venv python3-dev make rsync haveged jq"
 to_install=$(filter_packages debian-query $PACKAGE_LIST)
 
 echo "Installing: $to_install..."
@@ -64,4 +82,4 @@ if command -v systemctl > /dev/null; then # docker does not have systemctl
     sudo systemctl disable mosquitto
 fi
 
-
+exit 0
