npm path problem fix

diff --git a/bin/iot_install b/bin/iot_install
--- a/bin/iot_install
+++ b/bin/iot_install
@@ -94,6 +94,12 @@ function echo_message_read_answer() {
     esac
 }
 
+function init_nodejs() {
+    cd "$IOTEMPOWER_LOCAL" || { echo "$IOTEMPOWER_LOCAL not found, aborting." 1>&2;exit 1; }
+    mkdir -p nodejs && cd nodejs || { echo "Can't create nodejs folder, aborting." 1>&2;exit 1; }
+    npm init
+}
+
 # make installers available in PATH
 export PATH="$IOTEMPOWER_ROOT/lib/iot_installs:$PATH"
 
@@ -256,14 +262,14 @@ Do you want to install the fixed firmware?"
       #cd "$IOTEMPOWER_EXTERNAL/create_ap"
 
       # install node.js related stuff
-      cd "$IOTEMPOWER_LOCAL" || { echo "$IOTEMPOWER_LOCAL not found, aborting." 1>&2;exit 1; }
-      mkdir -p nodejs && cd nodejs || { echo "Can't create nodejs folder, aborting." 1>&2;exit 1; }
+      init_nodejs()
       npm install terminal-kit
 
-      echo "All necessary packages have been installed. The rest consists of optional packages."
+      echo "All core packages have been installed. The rest consists of optional packages."
     fi
 
     if [[ "$answer_commander" == 1 ]]; then
+      init_nodejs()
       echo "Installing Cloud Commander"
       # apt-get install g++ -y - Obsolete: should be in build-essential or default on arch
       npm install gritty
@@ -271,7 +277,6 @@ Do you want to install the fixed firmware?"
       # copy menu files
       cp -a "$IOTEMPOWER_ROOT/lib/gateway_setup/cloudcmd/cloudcmd.menu.js" "$HOME/.cloudcmd.menu.js"
       cp -a "$IOTEMPOWER_ROOT/lib/gateway_setup/cloudcmd/cloudcmd.json" "$HOME/.cloudcmd.json"
-
 
       cloudcmd_config=~/.cloudcmd.json
       jq '.auth = true | .prefix = "/cloudcmd" | .username = "iot" | '\
@@ -284,6 +289,7 @@ Do you want to install the fixed firmware?"
     fi
 
     if [[ "$answer_node_red" == 1 ]]; then
+      init_nodejs()
       echo "Installing Node Red"
       npm install --unsafe-perm node-red
       mkdir ~/.node-red/
