Remove fallback for IOTEMPOWER_MQTT_CERT_FOLDER and add error handling

diff --git a/bin/mqtt_broker b/bin/mqtt_broker
--- a/bin/mqtt_broker
+++ b/bin/mqtt_broker
@@ -59,6 +59,10 @@ EOF
     fi
 
     if [[ "$IOTEMPOWER_MQTT_USE_TLS" == 1 ]]; then
+        if [[ ! "$IOTEMPOWER_MQTT_CERT_FOLDER" ]]; then
+            echo "MQTT TLS enabled, but no certificate folder set. Aborting." 1>&2
+            exit 1
+        fi
     # IOTEMPOWER_MQTT_CERT_FOLDER's default is set in read_system_config
         cat << EOF >> "$APTEMP/mosquitto.conf"
 # TLS
diff --git a/bin/mqtt_listen b/bin/mqtt_listen
--- a/bin/mqtt_listen
+++ b/bin/mqtt_listen
@@ -44,6 +44,10 @@ fi
 
 ca_file_option=""
 if [[ "$IOTEMPOWER_MQTT_USE_TLS" == 1 ]]; then
+    if [[ ! "$IOTEMPOWER_MQTT_CERT_FOLDER" ]]; then
+        echo "MQTT TLS enabled, but no certificate folder set. Aborting." 1>&2
+        exit 1
+    fi
     ca_file_option=(--cafile "$IOTEMPOWER_MQTT_CERT_FOLDER/ca.crt")
 fi
 
