Allow rooms (traversal up to find system.conf)

diff --git a/bin/read_config b/bin/read_config
--- a/bin/read_config
+++ b/bin/read_config
@@ -1,15 +1,31 @@
 #@IgnoreInspection BashAddShebang
 # Read node and system configuration
 
-source "../system.conf" || { echo "Can't find system.conf. Aborting." 1>&2;exit 1; }
+[[ -e "node.conf" ]] || { echo "Can't find node.conf. Aborting." 1>&2;exit 1; }
+
+# search source.conf in parent directories and build a respective path to self
+# this search goes the following number of levels up max
+parent_levels=3
+path="$(pwd)"
+topic=$(basename "$(pwd)")
+while [[ ! -e "../system.conf" ]]; do
+    if [[ $parent_levels == 0 ]]; then
+        break
+    fi
+    cd ..
+    topic=$(basename "$(pwd)")"/$topic"
+    parent_levels=$(( $parent_levels - 1 ))
+done
+source "../system.conf" || { echo "Can't read system.conf. Aborting." 1>&2;exit 1; }
+
+cd "$path" # return to original path
 
 board="wemos d1 mini"
 
-topic=$(basename "$(pwd)")
 
 mqtt_server="$ULNOIOT_MQTT_HOST"
 mqtt_user="$ULNOIOT_MQTT_USER"
 mqtt_password="$ULNOIOT_MQTT_PW"
 
 
-source "node.conf" || { echo "Can't find node.conf. Aborting." 1>&2;exit 1; }
+source "node.conf" || { echo "Can't read node.conf. Aborting." 1>&2;exit 1; }
