command reference doen as draft

diff --git a/bin/ulnoiot_help b/bin/ulnoiot_help
--- a/bin/ulnoiot_help
+++ b/bin/ulnoiot_help
@@ -13,44 +13,50 @@ Display help on a specific command given in cmd. If cmd is empty, show this
 help. After entering the ulnoiot environment, this help is also available
 just via typing uhelp.
 
-[cmd] can be any of the following:
 EOF
-comma=""
-ls "$ULNOIOT_ROOT/$HELP_PATH/"*.txt | while read f; do
-    f=$(basename "$f")
-    if [[ ${f:0:1} != "_" ]]; then
-        echo -n $comma${f:0:-4}
-    fi
-    comma=", "
-done
-echo
-echo
-cat << EOF
-EOF
-exit 1
+# [cmd] can be any of the following:
 fi
 
+man -l "$ULNOIOT_LOCAL/doc/man/$1.1" 2>/dev/null || \
+    man -l "$ULNOIOT_LOCAL/doc/man/commands.1"
 
-cd "$ULNOIOT_ROOT"
+# obsolete
+# comma=""
+# ls "$ULNOIOT_ROOT/$HELP_PATH/"*.txt | while read f; do
+#     f=$(basename "$f")
+#     if [[ ${f:0:1} != "_" ]]; then
+#         echo -n $comma${f:0:-4}
+#     fi
+#     comma=", "
+# done
+# echo
+# echo
+# cat << EOF
+# EOF
+# exit 1
+# fi
 
-function help() {
-    local m
-    local p
-    local l
-    p="$ULNOIOT_ROOT/$HELP_PATH/$1.txt"
-    { cat "$p"; echo; } | while read l; do
-        if [[ "$l" = "!!"* ]]; then
-            if [[ "$l" =~ '!!help("'(.*)'")' ]]; then
-                m="${BASH_REMATCH[1]}"
-                help "$m"
-            else
-                echo "[[Cannot parse:"
-                echo "  ${l:2}]]"
-            fi
-        else
-            echo "$l"
-        fi
-    done
-}
 
-help "$1"
+# cd "$ULNOIOT_ROOT"
+
+# function help() {
+#     local m
+#     local p
+#     local l
+#     p="$ULNOIOT_ROOT/$HELP_PATH/$1.txt"
+#     { cat "$p"; echo; } | while read l; do
+#         if [[ "$l" = "!!"* ]]; then
+#             if [[ "$l" =~ '!!help("'(.*)'")' ]]; then
+#                 m="${BASH_REMATCH[1]}"
+#                 help "$m"
+#             else
+#                 echo "[[Cannot parse:"
+#                 echo "  ${l:2}]]"
+#             fi
+#         else
+#             echo "$l"
+#         fi
+#     done
+# }
+
+# help "$1"
