also set deafult auth for cloudcmd in config

diff --git a/bin/web_update_config b/bin/web_update_config
--- a/bin/web_update_config
+++ b/bin/web_update_config
@@ -1,5 +1,15 @@
 #!/bin/bash
 
+if [[ $# -gt 0 || "$*" = "help" || "$*" = "-h" || "$*" = "--help" ]]; then
+cat << EOF
+Syntax: web_update_config
+
+Set default configuration for node-red and cloudcmd.
+
+EOF
+exit 1
+fi
+
 nodered_config=~/.node-red/settings.js
 
 if ! grep -q "module.exports.httpAdminRoot = '/nodered';" "$nodered_config" ; then
@@ -21,5 +31,8 @@ fi
 
 cloudcmd_config=~/.cloudcmd.json
 
-jq '.prefix="/cloudcmd"' "$cloudcmd_config" > "$cloudcmd_config.new"
+jq '.prefix = "/cloudcmd" | .username = "iot" | '\
+'.password = "709d553e1a6e0b3f874408865d169870a945ceb25d72be561b7a50a23713d3452aea896e8e24783adcce86fddba087939ae3da9574997334e6362b5e767aa68a" | '\
+'.algo = "sha512WithRSAEncryption"' "$cloudcmd_config" > "$cloudcmd_config.new" || { echo "jq failed, aborting." 1>&2;exit 1; }
+mv "$cloudcmd_config" "$cloudcmd_config.backup"
 mv "$cloudcmd_config.new" "$cloudcmd_config"
