inproved WiFi setup CLI and Node-RED integration for Openwrt setup on Mango router

diff --git a/bin/wifi_openwrt_install b/bin/wifi_openwrt_install
--- a/bin/wifi_openwrt_install
+++ b/bin/wifi_openwrt_install
@@ -22,28 +22,12 @@ fi
 
 [ "$IOTEMPOWER_ACTIVE" = "yes" ] || { echo "IoTempower not active, aborting." 1>&2;exit 1; }
 #check if current router IP is correct
-#source $IOTEMPOWER_ROOT/bin/check_router_ip
+source $IOTEMPOWER_ROOT/bin/check_router_ip
 # Print it for verification
 #echo "Router IP: $ROUTER_IP"
 if [ -z "$ROUTER_IP" ]; then
     exit 1
 fi
-
-
-# Fetch the wifi credentials from etc/wifi_credentials
-
-source $IOTEMPOWER_ROOT/etc/wifi_credentials
-# Name of accesspoint to connect to
-echo "Your new AP SSID is: $IOTEMPOWER_AP_NAME"
-
-# IP to pick
-echo "Your new Gateway IP is: $IOTEMPOWER_AP_IP"
-
-# Connect data for local MQTT broker
-# If not defined, the same as IOTEMPOWERAP_IP from /etc/iotempower.conf default
-echo "Your new MQTT IP is: $IOTEMPOWER_MQTT_HOST"
-
-
 
 # Check if user has a public SSH key, if not create one
 if ls ~/.ssh/*.pub 1> /dev/null 2>&1 ; then 
@@ -57,26 +41,39 @@ fi
 #get routers inital ip from check_router_ip
 hostname="root@$ROUTER_IP"
 
-ssh -o HostKeyAlgorithms=+ssh-rsa -o PubkeyAcceptedKeyTypes=+ssh-rsa -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $hostname << EOF 
+echo "!!!!! This should only be runned on a Mango router - Gl Inet MT300N -V2 !!!!!"
+echo "!!!! It will install Openwrt 23.05.5 firmware version for this router!!!!"
+echo "!!!! If you run this on any other router, there is a high chance of bricking it!!!!"
+
+ read -p "Would you like to continue with installation? (yes/no) [no]: " response
+    response=${response:-no}
+
+  if [[ "$response" =~ ^[Yy][Ee][Ss]?$ ]]; then
+        ssh -o HostKeyAlgorithms=+ssh-rsa -o PubkeyAcceptedKeyTypes=+ssh-rsa -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $hostname << EOF 
 #echo "cpying your public key to the router authorized.keys for passwordless ssh loging..."
 echo $ssh_pub_key >> /etc/dropbear/authorized_keys
 
-# Verify wireless interface names
-uci show wireless
+ if ping -c 4 8.8.8.8 > /dev/null; then
+    echo "Router is connected to the internet."
+    break
+else
+    echo" The Router must have internet connection to run update"
+    echo "Please connect to the Internet via ETHERNET cable on WAN port"
+    exit 1
+fi
 
-uci set wireless.radio0.disabled='0'
-uci set wireless.default_radio0.ssid="$IOTEMPOWER_AP_NAME"
-uci set wireless.default_radio0.encryption="psk2"
-uci set wireless.default_radio0.key="$IOTEMPOWER_AP_PASSWORD"
-uci commit wireless
-wifi &
+# Installs Openwrt 23.05.5 firmware on a mango
 
-echo "Setting wifi credentials"
-uci set network.lan.ipaddr="$IOTEMPOWER_AP_IP"
-uci commit network
-echo "Setting network ip to $IOTEMPOWER_AP_IP and restarting..."
-echo "WiFi configuration has been written to uci config file"
-( sleep 5 ; /etc/init.d/network restart ) &
+cd /tmp
+wget http://downloads.openwrt.org/releases/23.05.5/targets/ramips/mt76x8/openwrt-23.05.5-ramips-mt76x8-glinet_gl-mt300n-v2-squashfs-sysupgrade.bin
+mtd -r write /tmp/openwrt-23.05.5-ramips-mt76x8-glinet_gl-mt300n-v2-squashfs-sysupgrade.bin firmware
 
 EOF
+
+else
+# If the user does not want to continue with the installation
+echo "Installation aborted"
+exit 1
+fi
+
 
diff --git a/bin/wifi_openwrt_uci b/bin/wifi_openwrt_uci
--- a/bin/wifi_openwrt_uci
+++ b/bin/wifi_openwrt_uci
@@ -22,7 +22,7 @@ fi
 
 [ "$IOTEMPOWER_ACTIVE" = "yes" ] || { echo "IoTempower not active, aborting." 1>&2;exit 1; }
 #check if current router IP is correct
-source $IOTEMPOWER_ROOT/bin/check_router_ip
+#source $IOTEMPOWER_ROOT/bin/check_router_ip
 # Print it for verification
 #echo "Router IP: $ROUTER_IP"
 if [ -z "$ROUTER_IP" ]; then
@@ -30,7 +30,7 @@ if [ -z "$ROUTER_IP" ]; then
 fi
 
 # Prompt the user for SSID and password
-source $IOTEMPOWER_ROOT/bin/wifi_credentials_temp
+#source $IOTEMPOWER_ROOT/bin/wifi_credentials_temp
 source $IOTEMPOWER_ROOT/etc/wifi_credentials
 
 # Check if user has a public SSH key, if not create one
@@ -115,13 +115,18 @@ wifi &
 echo "Setting wifi credentials"
 uci set network.lan.ipaddr="$IOTEMPOWER_AP_IP"
 uci commit network
-echo "Setting network ip to 192.168.14.1 and restarting..."
+echo "Setting network ip to $IOTEMPOWER_AP_IP and restarting..."
 echo "WiFi configuration has been written to uci config file"
 ( sleep 5 ; /etc/init.d/network restart ) &
 
 EOF
-# TODO deactivate dropbear
-#TODO some mechanism that detacts if the router has internet and only run the install if it does
-echo "Please restart the router to apply the changes and connect to the new wifi network $IOTEMPOWER_AP_IP"
 
-echo "Done"
+ if [[ $? -eq 0 ]]; then
+        # Write settings to the system.conf files
+      echo "Please restart the router to apply the changes and connect to the new wifi network $IOTEMPOWER_AP_IP"
+    else
+        echo "wifi_openwrt_uci command failed. Aborting."
+        exit 1
+    fi
+# TODO deactivate dropbear
+
diff --git a/bin/wifi_update_openwrt b/bin/wifi_update_openwrt
--- a/bin/wifi_update_openwrt
+++ b/bin/wifi_update_openwrt
@@ -23,8 +23,20 @@ fi
 [ "$IOTEMPOWER_ACTIVE" = "yes" ] || { echo "IoTempower not active, aborting." 1>&2;exit 1; }
 
 if [[ -e "system.conf" ]]; then  # started from system-directory
+    # Check if router is connected
+    . $IOTEMPOWER_ROOT/bin/check_router_ip
+    # Prompt the user for SSID and password
+    . $IOTEMPOWER_ROOT/bin/wifi_credentials_temp
+    # Write settings to the router via uci
     . $IOTEMPOWER_ROOT/bin/wifi_openwrt_change_uci
-    . $IOTEMPOWER_ROOT/bin/setup_systemconf
+   # Check if the wifi_openwrt_uci command was successful
+    if [[ $? -eq 0 ]]; then
+        # Write settings to the system.conf files
+        . $IOTEMPOWER_ROOT/bin/setup_systemconf
+    else
+        echo "wifi_openwrt_uci command failed. Aborting."
+        exit 1
+    fi
 else
     echo "You must be inside a system folder (or it's subfolders) to run this script"
     echo "It must contain a file named system.conf"
