updated scripts for openwrt router setup

diff --git a/bin/wifi_setup_openwrt b/bin/wifi_setup_openwrt
--- a/bin/wifi_setup_openwrt
+++ b/bin/wifi_setup_openwrt
@@ -22,6 +22,16 @@ fi
 
 [ "$IOTEMPOWER_ACTIVE" = "yes" ] || { echo "IoTempower not active, aborting." 1>&2;exit 1; }
 echo "Setting up external OpenWRT router for IoTempower using wifi_cedentials from /etc/wifi_credentials"
-. $IOTEMPOWER_ROOT/bin/wifi_credentials
-. $IOTEMPOWER_ROOT/bin/wifi_openwrt_uci
-. $IOTEMPOWER_ROOT/bin/setup_systemconf
+if [[ -e "system.conf" ]]; then  # started from system-directory
+    . $IOTEMPOWER_ROOT/bin/wifi_openwrt_uci
+    . $IOTEMPOWER_ROOT/bin/setup_systemconf
+
+
+else
+    echo "You must be inside a system folder (or it's subfolders) to run this script"
+    echo "It must contain a file named system.conf"
+    echo "Please navigate to a IoT system folder (ussually in iot-system/your project) and try again"
+     echo "No system.conf found, aborting."
+    exit 1
+fi
+
