add node install with nvm to arch

diff --git a/lib/iot_installs/arch-install-general b/lib/iot_installs/arch-install-general
--- a/lib/iot_installs/arch-install-general
+++ b/lib/iot_installs/arch-install-general
@@ -32,6 +32,41 @@ else
     [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
 fi
 
+# Define the minimum required version
+min_version="21"
+
+function check_node() {
+    # check nodejs version
+    if command -v node &> /dev/null; then
+        installed_version=$(node -v 2>/dev/null| sed 's/v//') # Remove the 'v' prefix from version
+    else
+        installed_version="0.0.0-notinstalled"
+    fi
+    # Use sort with version sort flag to compare versions, and check the first line
+    if [[ "$installed_version" && "$(printf "%s\n%s" "$min_version" "$installed_version" | sort -V | head -n1)" = "$min_version" ]]; then
+        if [ "$installed_version" = "$min_version" ] || [ "$(printf "%s\n%s" "$min_version" "$installed_version" | sort -V | head -n2 | tail -n1)" = "$installed_version" ]; then
+            echo "Node.js version $installed_version is installed, meets the minimum required version $min_version."
+        else
+            echo "Node.js version is higher than the minimum required version $min_version."
+        fi
+        return 0 # all good
+    else
+        echo "Node.js version is $installed_version, and "
+        echo "does not meet the minimum required version $min_version."
+        return 1
+    fi
+}
+
+if ! check_node; then
+   
+    echo "Trying to install current node version."
+    nvm install $min_version
+    if ! check_node; then
+        echo "A current node version could not be installed."
+        exit 1
+    fi
+fi
+
 # curl git mosquitto python-virtualenv rsync haveged jq # general
 # ./arch-install iptables bridge-utils hostapd dnsmasq # router and networking
 
